runtime_root="${PROJECTORCTL_RUNTIME_DIR:-${XDG_RUNTIME_DIR:-/tmp}/projector-control-${UID}}"
hypr_root="${PROJECTORCTL_HYPR_ROOT:-${XDG_RUNTIME_DIR:-/tmp}/hypr}"
drm_root="${PROJECTORCTL_DRM_ROOT:-/sys/class/drm}"
state_file="$runtime_root/state.json"
layout_file="${PROJECTORCTL_LAYOUT_FILE:-${XDG_RUNTIME_DIR:-$runtime_root}/projector-layout.lua}"
private_layout_file="${PROJECTORCTL_PRIVATE_LAYOUT_FILE:-${HOME}/.cache/hypr/projector-private-layout.lua}"
operation_lock="$runtime_root/operation.lock"
guard_lock="$runtime_root/guard.lock"
pending_guard_file="$runtime_root/recovery.pending"
guard_event_fifo="$runtime_root/guard.events"

hyprctl_bin="${PROJECTORCTL_HYPRCTL:-hyprctl}"
caelestia_bin="${PROJECTORCTL_CAELESTIA:-caelestia}"
notify_bin="${PROJECTORCTL_NOTIFY_SEND:-notify-send}"
udevadm_bin="${PROJECTORCTL_UDEVADM:-udevadm}"
guard_poll_interval="${PROJECTORCTL_GUARD_POLL_INTERVAL:-60}"
monitor_timeout="${PROJECTORCTL_MONITOR_TIMEOUT:-3}"
monitor_probe_timeout="${PROJECTORCTL_MONITOR_PROBE_TIMEOUT:-0.5}"
verification_attempts="${PROJECTORCTL_VERIFICATION_ATTEMPTS:-10}"
guard_retry_interval="${PROJECTORCTL_GUARD_RETRY_INTERVAL:-1}"
watcher_health_interval="${PROJECTORCTL_WATCHER_HEALTH_INTERVAL:-5}"

internal_pattern='^(eDP|LVDS|DSI)(-|$)'
ignored_output_pattern='^(HEADLESS|FALLBACK)(-|$)'
BUILTIN_OUTPUT=""
EXTERNAL_OUTPUT=""
LAST_ERROR=""
RECOVERY_NOTICE=""

mkdir -p "$runtime_root"
